public class Main {
    public static void main(String[] args) {
        System.out.println("Задача 1");
        var dog = 8;
        var cat = 3.6;
        var paper = 763789;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        System.out.println("Задача 2");
        dog = dog + 4;
        cat = cat + 4;
        paper = paper + 4;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        System.out.println("Задача 3");
        System.out.println("Из-за того, что условия задачи были неточны, было использовано предложение целого числа");
        dog = (int) (dog - 3.5);
        cat = cat - 1.6;
        paper = paper - 7639;
        System.out.println(dog);
        System.out.println(cat);
        System.out.println(paper);
        System.out.println("Задача 4");
        var friend = 19;
        System.out.println(friend);
        friend = friend + 2;
        System.out.println(friend);
        friend = friend / 7;
        System.out.println(friend);
        System.out.println("Задача 5");
        var frog = 3.5;
        System.out.println(frog);
        frog = frog * 10;
        System.out.println(frog);
        frog = frog / 3.5;
        System.out.println(frog);
        frog = frog + 4;
        System.out.println(frog);
        System.out.println("Задача 6");
        var firstBoxer = 78.2;
        var secondBoxer = 82.7;
        var totalWeight = firstBoxer + secondBoxer;
        System.out.println("Общий вес боксеров " + totalWeight + " кг");
        var difference = firstBoxer - secondBoxer;
        System.out.println("Разница между весами бойцов " + difference + " кг");
        System.out.println("Задача 7");
        var differenceNew = secondBoxer - firstBoxer;
        System.out.println("Разница весов спортсменов " + differenceNew + " кг");
        var differenceNew1 = secondBoxer % firstBoxer;
        System.out.println("Разница весов спортсменов на " + differenceNew1 + " кг");
        System.out.println("Задача 8");
        var totalHours = 640;
        var everyEmployeeWorks = 8;
        var totalEmployees = totalHours / everyEmployeeWorks;
        System.out.println("Всего работников в компании - " + totalEmployees + " человек ");
        var employeesVer2 = 94;
        var totalEmployeesNew = totalEmployees + employeesVer2;
        var totalHoursNew = totalEmployeesNew * everyEmployeeWorks;
        System.out.println("Если в компании работает " + totalEmployeesNew + " человек, " + "то всего " + totalHoursNew + " часов работы может быть поделено между сотрудниками ");
    }
}